### PR TITLE
Class Decorator Ruby project module Four 

### PR DESCRIPTION
**Pull request by juaryimami**
### In this project, 
---
- I use the Decorator design pattern to correct the names of people.
- I understand the concept of inheritance and composition in deep.
---
#### Thank you for reviewing my project!!!!.

### CODE REVIEW

**Review by jerryowusu — COMMENTED** [review]
Hi @juaryimami , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

invalid


## Invalid Code Review Request

You have submitted a pull request using github flow, however, the project requires you to use gitflow. Kindly update accordingly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by juaryimami** [comment]
its contradictory...?

**Review by rloterh — COMMENTED** [review]
Hi Juhar, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the merge request for this activity should flow **from feature into development**. Kindly use the correct gitflow.

Kindly also ensure that provided text instructions are removed and replaced with appropriate contents applicable under each section of your ReadMe.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by juaryimami** [comment]
its my right to use realease brach why you block my approval? can you explain it the reson why I could not use release branch?

**Comment by rloterh** [comment]
@juaryimami 
Kindly note that for the above project, we recommend using a _feature into development_ merge request. This is because the bigger picture of this project is divided into sub modules/activities, meaning we'll merge our smaller changes from _feature into development_ branch. <br>

It's then appropriate to merge our final or fully functioning app from _development into main_ branch, which you'll mostly often showcase. Please find out more via [this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). 

Cheers! 😃

**Pull request closed without merging**
